### PR TITLE
Deleted Socket, and fixed Tests

### LINKED ISSUE #197: Delete Sockets from EV and Chargers
As we have figured out that all newer cars all use the same socket, there is no reason for us to implement and use different sockets. Because of that we need to delete the implementation we have of Sockets.

### PR DESCRIPTION
**Pull request by DanielRBech**
# Related Issues

Closes #197 

## Description of Implementation (optional)

Deleted the Socket class and removed everything related to that, while keeping most of the same logic for charging a car.

## Pre-PR Checklist
Ensure these are completed before opening the PR:

- [X] All new and modified code has been tested (explain in Notes if not tested)  
- [X] Self-review completed

### CODE REVIEW

**Review by Tbjerregaard — APPROVED** [review]

File: Engine/Cost/ComputeCost.cs [hunk 1]
```diff
@@ -63,18 +63,10 @@ public Station Compute(ref EV ev, Dictionary<ushort, float> stationDurations, Ti
...
-
-        if (supportingChargers == 0)
-        {
-            // Station doesn't support this socket type—return infinite cost to exclude it
-            return float.MaxValue;
-        }
-
-        var totalQueueSize = stationService.GetTotalQueueSize(station.Id);
-        var effectiveQueueSize = (float)totalQueueSize / station.Chargers.Count(s => s.GetSockets().Contains(socket));
+        var totalQueueSize = stationService.GetTotalQueueSize(station.Id) + 0.01f;
```
Comment (NiklasBH) [inline Engine/Cost/ComputeCost.cs]: no need for +0.01

File: Engine/DayCycles/CarsOnRoad.cs [hunk 2]
```diff
@@ -9,7 +9,7 @@ public static class CarsOnRoad
     /// Total registered EVs in Denmark according to DST - January 2026 (Rounded down).
     /// Source: https://www.dst.dk/da/Statistik/udgivelser/NytHtml?cid=51885.
     /// </summary>
-    public const int TotalEVs = 556000;
+    public const int TotalEVs = 583320;
```
Comment (NiklasBH) [inline Engine/DayCycles/CarsOnRoad.cs:11]: Update summary above to match

**Review by NiklasBH — APPROVED** [review]

**Review by MertzAndreas — CHANGES_REQUESTED** [review]
Fix connectors

**Review by MertzAndreas — APPROVED** [review]
